//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : SmcLineCheckerFsm.sm
//

#include "SmcLineChecker.h"
#include "SmcLineCheckerFsm.h"

using namespace statemap;

namespace LineChecker
{
    // Static class declarations.
    Cases_LineNumber Cases::LineNumber("Cases::LineNumber", 0);
    Cases_Spaces1 Cases::Spaces1("Cases::Spaces1", 1);
    Cases_Var1 Cases::Var1("Cases::Var1", 2);
    Cases_Spaces2 Cases::Spaces2("Cases::Spaces2", 3);
    Cases_Assignment Cases::Assignment("Cases::Assignment", 4);
    Cases_UnaryMinus1 Cases::UnaryMinus1("Cases::UnaryMinus1", 5);
    Cases_Number1 Cases::Number1("Cases::Number1", 6);
    Cases_Spaces3 Cases::Spaces3("Cases::Spaces3", 7);
    Cases_Var2 Cases::Var2("Cases::Var2", 8);
    Cases_Spaces4 Cases::Spaces4("Cases::Spaces4", 9);
    Cases_Operation Cases::Operation("Cases::Operation", 10);
    Cases_Spaces5 Cases::Spaces5("Cases::Spaces5", 11);
    Cases_UnaryMinus2 Cases::UnaryMinus2("Cases::UnaryMinus2", 12);
    Cases_Number2 Cases::Number2("Cases::Number2", 13);
    Cases_Var3 Cases::Var3("Cases::Var3", 14);
    Cases_Spaces6 Cases::Spaces6("Cases::Spaces6", 15);
    Cases_Error Cases::Error("Cases::Error", 16);

    void SmcLineCheckerState::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        Default(context);
    }

    void SmcLineCheckerState::reset(SmcLineCheckerFsm& context)
    {
        Default(context);
    }

    void SmcLineCheckerState::Default(SmcLineCheckerFsm& context)
    {
        throw (
            TransitionUndefinedException(
                (context.getState()).getName(),
                context.getTransition()));

    }

    void Cases_LineNumber::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isdigit(ch) )
        {
            // No actions.
        }
        else if (std::isspace(ch) )
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Spaces1);
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Spaces1::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isspace(ch) )
        {
            // No actions.
        }
        else if (std::isalpha(ch) )
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.var1PushChar(ch);
                context.setState(Cases::Var1);
            }
            catch (...)
            {
                context.setState(Cases::Var1);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Var1::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (ch == '=')
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Assignment);
            context.getState().Entry(context);
        }
        else if (std::isalpha(ch) && ctxt.var1Size() < 15)
    
    {
            SmcLineCheckerState& endState = context.getState();

            context.clearState();
            try
            {
                ctxt.var1PushChar(ch);
                context.setState(endState);
            }
            catch (...)
            {
                context.setState(endState);
                throw;
            }
        }
        else if (std::isdigit(ch)  && ctxt.var1Size() < 15)
    
    {
            SmcLineCheckerState& endState = context.getState();

            context.clearState();
            try
            {
                ctxt.var1PushChar(ch);
                context.setState(endState);
            }
            catch (...)
            {
                context.setState(endState);
                throw;
            }
        }
        else if (std::isspace(ch))
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Spaces2);
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Spaces2::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isspace(ch) )
        {
            // No actions.
        }
        else if (ch == '=')
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Assignment);
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Assignment::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isalpha(ch) )
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.var2PushChar(ch);
                context.setState(Cases::Var2);
            }
            catch (...)
            {
                context.setState(Cases::Var2);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (std::isdigit(ch) )
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setDone();
                context.setState(Cases::Number1);
            }
            catch (...)
            {
                context.setState(Cases::Number1);
                throw;
            }
            context.getState().Entry(context);
        }
        else if ( ch == '-' )
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::UnaryMinus1);
            context.getState().Entry(context);
        }
        else if (std::isspace(ch) )
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Spaces3);
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_UnaryMinus1::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isalpha(ch) )
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.var2PushChar(ch);
                context.setState(Cases::Var2);
            }
            catch (...)
            {
                context.setState(Cases::Var2);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (std::isdigit(ch) )
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setDone();
                context.setState(Cases::Number1);
            }
            catch (...)
            {
                context.setState(Cases::Number1);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Number1::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isdigit(ch) )
        {
            // No actions.
        }
        else if (std::isspace(ch) )
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Spaces4);
            context.getState().Entry(context);
        }
        else if (ch == '+' || ch == '-' || ch == '/' || ch == '*')
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setNotDone();
                context.setState(Cases::Operation);
            }
            catch (...)
            {
                context.setState(Cases::Operation);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Spaces3::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isspace(ch) )
        {
            // No actions.
        }
        else if ( ch == '-' )
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::UnaryMinus1);
            context.getState().Entry(context);
        }
        else if (std::isdigit(ch))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setDone();
                context.setState(Cases::Number1);
            }
            catch (...)
            {
                context.setState(Cases::Number1);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (std::isalpha(ch))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.var2PushChar(ch);
                ctxt.setDone();
                context.setState(Cases::Var2);
            }
            catch (...)
            {
                context.setState(Cases::Var2);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Var2::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isalpha(ch) && ctxt.var2Size() < 15)
        {
            SmcLineCheckerState& endState = context.getState();

            context.clearState();
            try
            {
                ctxt.var2PushChar(ch);
                context.setState(endState);
            }
            catch (...)
            {
                context.setState(endState);
                throw;
            }
        }
        else if (std::isdigit(ch)  && ctxt.var2Size() < 15)
    
    {
            SmcLineCheckerState& endState = context.getState();

            context.clearState();
            try
            {
                ctxt.var2PushChar(ch);
                context.setState(endState);
            }
            catch (...)
            {
                context.setState(endState);
                throw;
            }
        }
        else if (std::isspace(ch))
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Spaces4);
            context.getState().Entry(context);
        }
        else if (ch == '+' || ch == '-' || ch == '/' || ch == '*')
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setNotDone();
                context.setState(Cases::Operation);
            }
            catch (...)
            {
                context.setState(Cases::Operation);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Spaces4::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isspace(ch) )
        {
            // No actions.
        }
        else if (ch == '+' || ch == '-' || ch == '/' || ch == '*')
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setNotDone();
                context.setState(Cases::Operation);
            }
            catch (...)
            {
                context.setState(Cases::Operation);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Operation::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isspace(ch))
        {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Spaces5);
            context.getState().Entry(context);
        }
        else if (std::isalpha(ch))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.var3PushChar(ch);
                ctxt.setDone();
                context.setState(Cases::Var3);
            }
            catch (...)
            {
                context.setState(Cases::Var3);
                throw;
            }
            context.getState().Entry(context);
        }
        else if ( ch == '-' )
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::UnaryMinus2);
            context.getState().Entry(context);
        }
        else if (std::isdigit(ch))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setDone();
                context.setState(Cases::Number2);
            }
            catch (...)
            {
                context.setState(Cases::Number2);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Spaces5::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isspace(ch) )
        {
            // No actions.
        }
        else if (std::isalpha(ch))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.var3PushChar(ch);
                ctxt.setDone();
                context.setState(Cases::Var3);
            }
            catch (...)
            {
                context.setState(Cases::Var3);
                throw;
            }
            context.getState().Entry(context);
        }
        else if ( ch == '-' )
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::UnaryMinus1);
            context.getState().Entry(context);
        }
        else if (std::isdigit(ch))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setDone();
                context.setState(Cases::Number2);
            }
            catch (...)
            {
                context.setState(Cases::Number2);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_UnaryMinus2::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isalpha(ch))
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.var3PushChar(ch);
                ctxt.setDone();
                context.setState(Cases::Var3);
            }
            catch (...)
            {
                context.setState(Cases::Var3);
                throw;
            }
            context.getState().Entry(context);
        }
        else if (std::isdigit(ch))
    
    {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setDone();
                context.setState(Cases::Number2);
            }
            catch (...)
            {
                context.setState(Cases::Number2);
                throw;
            }
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Number2::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isdigit(ch))
        {
            // No actions.
        }
        else if (std::isspace(ch))
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Spaces6);
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Var3::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isalpha(ch) || std::isdigit(ch))
        {
            SmcLineCheckerState& endState = context.getState();

            context.clearState();
            try
            {
                ctxt.var3PushChar(ch);
                context.setState(endState);
            }
            catch (...)
            {
                context.setState(endState);
                throw;
            }
        }
        else if (std::isspace(ch))
    
    {
            context.getState().Exit(context);
            // No actions.
            context.setState(Cases::Spaces6);
            context.getState().Entry(context);
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Spaces6::checkNext(SmcLineCheckerFsm& context, char ch)
    {
        SmcLineChecker& ctxt = context.getOwner();

        if (std::isspace(ch) )
        {
            // No actions.
        }
        else
        {
            context.getState().Exit(context);
            context.clearState();
            try
            {
                ctxt.setInCorrect();
                context.setState(Cases::Error);
            }
            catch (...)
            {
                context.setState(Cases::Error);
                throw;
            }
            context.getState().Entry(context);
        }

    }

    void Cases_Spaces6::reset(SmcLineCheckerFsm& context)
    {
        SmcLineChecker& ctxt = context.getOwner();

        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.resetFSM();
            context.setState(Cases::LineNumber);
        }
        catch (...)
        {
            context.setState(Cases::LineNumber);
            throw;
        }
        context.getState().Entry(context);


    }

    void Cases_Error::reset(SmcLineCheckerFsm& context)
    {
        SmcLineChecker& ctxt = context.getOwner();

        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.resetFSM();
            context.setState(Cases::LineNumber);
        }
        catch (...)
        {
            context.setState(Cases::LineNumber);
            throw;
        }
        context.getState().Entry(context);


    }
}

//
// Local variables:
//  buffer-read-only: t
// End:
//
