//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : SmcLineCheckerFsm.sm
//

#ifndef SMCLINECHECKERFSM_H
#define SMCLINECHECKERFSM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace LineChecker
{
    // Forward declarations.
    class Cases;
    class Cases_LineNumber;
    class Cases_Spaces1;
    class Cases_Var1;
    class Cases_Spaces2;
    class Cases_Assignment;
    class Cases_UnaryMinus1;
    class Cases_Number1;
    class Cases_Spaces3;
    class Cases_Var2;
    class Cases_Spaces4;
    class Cases_Operation;
    class Cases_Spaces5;
    class Cases_UnaryMinus2;
    class Cases_Number2;
    class Cases_Var3;
    class Cases_Spaces6;
    class Cases_Error;
    class Cases_Default;
    class SmcLineCheckerState;
    class SmcLineCheckerFsm;
    class SmcLineChecker;

    class SmcLineCheckerState :
        public statemap::State
    {
    public:

        SmcLineCheckerState(const char * const name, const int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(SmcLineCheckerFsm&) {};
        virtual void Exit(SmcLineCheckerFsm&) {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
        virtual void reset(SmcLineCheckerFsm& context);

    protected:

        virtual void Default(SmcLineCheckerFsm& context);
    };

    class Cases
    {
    public:

        static Cases_LineNumber LineNumber;
        static Cases_Spaces1 Spaces1;
        static Cases_Var1 Var1;
        static Cases_Spaces2 Spaces2;
        static Cases_Assignment Assignment;
        static Cases_UnaryMinus1 UnaryMinus1;
        static Cases_Number1 Number1;
        static Cases_Spaces3 Spaces3;
        static Cases_Var2 Var2;
        static Cases_Spaces4 Spaces4;
        static Cases_Operation Operation;
        static Cases_Spaces5 Spaces5;
        static Cases_UnaryMinus2 UnaryMinus2;
        static Cases_Number2 Number2;
        static Cases_Var3 Var3;
        static Cases_Spaces6 Spaces6;
        static Cases_Error Error;
    };

    class Cases_Default :
        public SmcLineCheckerState
    {
    public:

        Cases_Default(const char * const name, const int stateId)
        : SmcLineCheckerState(name, stateId)
        {};

    };

    class Cases_LineNumber :
        public Cases_Default
    {
    public:
        Cases_LineNumber(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Spaces1 :
        public Cases_Default
    {
    public:
        Cases_Spaces1(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Var1 :
        public Cases_Default
    {
    public:
        Cases_Var1(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Spaces2 :
        public Cases_Default
    {
    public:
        Cases_Spaces2(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Assignment :
        public Cases_Default
    {
    public:
        Cases_Assignment(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_UnaryMinus1 :
        public Cases_Default
    {
    public:
        Cases_UnaryMinus1(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Number1 :
        public Cases_Default
    {
    public:
        Cases_Number1(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Spaces3 :
        public Cases_Default
    {
    public:
        Cases_Spaces3(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Var2 :
        public Cases_Default
    {
    public:
        Cases_Var2(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Spaces4 :
        public Cases_Default
    {
    public:
        Cases_Spaces4(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Operation :
        public Cases_Default
    {
    public:
        Cases_Operation(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Spaces5 :
        public Cases_Default
    {
    public:
        Cases_Spaces5(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_UnaryMinus2 :
        public Cases_Default
    {
    public:
        Cases_UnaryMinus2(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Number2 :
        public Cases_Default
    {
    public:
        Cases_Number2(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Var3 :
        public Cases_Default
    {
    public:
        Cases_Var3(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
    };

    class Cases_Spaces6 :
        public Cases_Default
    {
    public:
        Cases_Spaces6(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void checkNext(SmcLineCheckerFsm& context, char ch);
        virtual void reset(SmcLineCheckerFsm& context);
    };

    class Cases_Error :
        public Cases_Default
    {
    public:
        Cases_Error(const char * const name, const int stateId)
        : Cases_Default(name, stateId)
        {};

        virtual void reset(SmcLineCheckerFsm& context);
    };

    class SmcLineCheckerFsm :
        public statemap::FSMContext
    {
    public:

        explicit SmcLineCheckerFsm(SmcLineChecker& owner)
        : FSMContext(Cases::LineNumber),
          _owner(owner)
        {};

        SmcLineCheckerFsm(SmcLineChecker& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        inline SmcLineChecker& getOwner()
        {
            return (_owner);
        };

        inline SmcLineCheckerState& getState()
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return dynamic_cast<SmcLineCheckerState&>(*_state);
        };

        inline void checkNext(char ch)
        {
            getState().checkNext(*this, ch);
        };

        inline void reset()
        {
            getState().reset(*this);
        };

    private:
        SmcLineChecker& _owner;
    };
}


#endif // SMCLINECHECKERFSM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
