// Code generated by golex. DO NOT EDIT.

package main

import (
	"bufio"
	"strconv"
)

import (
	intr "lab3/interpreter"
)

type lexerCtx struct {
	src     *bufio.Reader
	buf     []byte
	current byte
}

func (l *lexerCtx) getc() byte {
	// fmt.Println("sybol is ", string(l.current), l.current)
	if l.current != 0 {
		l.buf = append(l.buf, l.current)
	}
	l.current = 0
	if b, err := l.src.ReadByte(); err == nil {
		l.current = b
	}
	return l.current

}

func (l *lexerCtx) Lex(lval *yySymType) int {
	return l.yyLex(lval)
}

func (l *lexerCtx) yyLex(yyLval *yySymType) int {

yystate0:

	// Перед распознаванием токена golex фиксирует начальную позицию
	l.buf = l.buf[:0]

	goto yystart1

yystate1:
	l.current = l.getc()
yystart1:
	switch {
	default:
		goto yystate3 // l.current >= '\x01' && l.current <= '\b' || l.current == '\v' || l.current == '\f' || l.current >= '\x0e' && l.current <= '\x1f' || l.current >= '"' && l.current <= '%%' || l.current == '\'' || l.current == '.' || l.current == ':' || l.current == '<' || l.current >= '>' && l.current <= '@' || l.current == '\\' || l.current == '^' || l.current == '`' || l.current == '|' || l.current >= '~' && l.current <= 'ÿ'
	case l.current == '!':
		goto yystate6
	case l.current == '&':
		goto yystate7
	case l.current == '(':
		goto yystate9
	case l.current == ')':
		goto yystate10
	case l.current == '*':
		goto yystate11
	case l.current == '+':
		goto yystate12
	case l.current == ',':
		goto yystate13
	case l.current == '-':
		goto yystate14
	case l.current == '/':
		goto yystate15
	case l.current == ';':
		goto yystate18
	case l.current == '=':
		goto yystate19
	case l.current == '[':
		goto yystate22
	case l.current == '\n':
		goto yystate5
	case l.current == '\t' || l.current == '\r' || l.current == ' ':
		goto yystate4
	case l.current == '\x00':
		goto yystate2
	case l.current == ']':
		goto yystate23
	case l.current == 'c':
		goto yystate24
	case l.current == 'd':
		goto yystate29
	case l.current == 'e':
		goto yystate34
	case l.current == 'f':
		goto yystate36
	case l.current == 'g':
		goto yystate43
	case l.current == 'l':
		goto yystate46
	case l.current == 'm':
		goto yystate53
	case l.current == 'o':
		goto yystate59
	case l.current == 'p':
		goto yystate68
	case l.current == 'r':
		goto yystate84
	case l.current == 's':
		goto yystate104
	case l.current == 't':
		goto yystate124
	case l.current == '{':
		goto yystate150
	case l.current == '}':
		goto yystate151
	case l.current >= '0' && l.current <= '9':
		goto yystate16
	case l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current == 'a' || l.current == 'b' || l.current >= 'h' && l.current <= 'k' || l.current == 'n' || l.current == 'q' || l.current >= 'u' && l.current <= 'z':
		goto yystate20
	}

yystate2:
	l.current = l.getc()
	goto yyrule48

yystate3:
	l.current = l.getc()
	goto yyrule49

yystate4:
	l.current = l.getc()
	switch {
	default:
		goto yyrule1
	case l.current == '\t' || l.current == '\n' || l.current == '\r' || l.current == ' ':
		goto yystate5
	}

yystate5:
	l.current = l.getc()
	switch {
	default:
		goto yyrule1
	case l.current == '\t' || l.current == '\n' || l.current == '\r' || l.current == ' ':
		goto yystate5
	}

yystate6:
	l.current = l.getc()
	goto yyrule29

yystate7:
	l.current = l.getc()
	switch {
	default:
		goto yyrule49
	case l.current == '&':
		goto yystate8
	}

yystate8:
	l.current = l.getc()
	goto yyrule30

yystate9:
	l.current = l.getc()
	goto yyrule17

yystate10:
	l.current = l.getc()
	goto yyrule18

yystate11:
	l.current = l.getc()
	goto yyrule4

yystate12:
	l.current = l.getc()
	goto yyrule2

yystate13:
	l.current = l.getc()
	goto yyrule27

yystate14:
	l.current = l.getc()
	goto yyrule3

yystate15:
	l.current = l.getc()
	goto yyrule5

yystate16:
	l.current = l.getc()
	switch {
	default:
		goto yyrule46
	case l.current >= '0' && l.current <= '9':
		goto yystate17
	}

yystate17:
	l.current = l.getc()
	switch {
	default:
		goto yyrule46
	case l.current >= '0' && l.current <= '9':
		goto yystate17
	}

yystate18:
	l.current = l.getc()
	goto yyrule28

yystate19:
	l.current = l.getc()
	goto yyrule21

yystate20:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate21:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate22:
	l.current = l.getc()
	goto yyrule13

yystate23:
	l.current = l.getc()
	goto yyrule14

yystate24:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'h':
		goto yystate25
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'g' || l.current >= 'i' && l.current <= 'z':
		goto yystate21
	}

yystate25:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate26
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate26:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'c':
		goto yystate27
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current == 'a' || l.current == 'b' || l.current >= 'd' && l.current <= 'z':
		goto yystate21
	}

yystate27:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'k':
		goto yystate28
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'j' || l.current >= 'l' && l.current <= 'z':
		goto yystate21
	}

yystate28:
	l.current = l.getc()
	switch {
	default:
		goto yyrule35
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate29:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate30
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate30:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'g':
		goto yystate31
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'f' || l.current >= 'h' && l.current <= 'z':
		goto yystate21
	}

yystate31:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate32
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate32:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate33
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate33:
	l.current = l.getc()
	switch {
	default:
		goto yyrule19
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate34:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'q':
		goto yystate35
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'p' || l.current >= 'r' && l.current <= 'z':
		goto yystate21
	}

yystate35:
	l.current = l.getc()
	switch {
	default:
		goto yyrule22
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate36:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'a':
		goto yystate37
	case l.current == 'o':
		goto yystate41
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'b' && l.current <= 'n' || l.current >= 'p' && l.current <= 'z':
		goto yystate21
	}

yystate37:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'l':
		goto yystate38
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'k' || l.current >= 'm' && l.current <= 'z':
		goto yystate21
	}

yystate38:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 's':
		goto yystate39
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'r' || l.current >= 't' && l.current <= 'z':
		goto yystate21
	}

yystate39:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate40
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate40:
	l.current = l.getc()
	switch {
	default:
		goto yyrule7
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate41:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'r':
		goto yystate42
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate42:
	l.current = l.getc()
	switch {
	default:
		goto yyrule32
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate43:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate44
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate44:
	l.current = l.getc()
	switch {
	default:
		goto yyrule25
	case l.current == 'e':
		goto yystate45
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate45:
	l.current = l.getc()
	switch {
	default:
		goto yyrule26
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate46:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'o':
		goto yystate47
	case l.current == 't':
		goto yystate51
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'n' || l.current >= 'p' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate47:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'g':
		goto yystate48
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'f' || l.current >= 'h' && l.current <= 'z':
		goto yystate21
	}

yystate48:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate49
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate49:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'c':
		goto yystate50
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current == 'a' || l.current == 'b' || l.current >= 'd' && l.current <= 'z':
		goto yystate21
	}

yystate50:
	l.current = l.getc()
	switch {
	default:
		goto yyrule20
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate51:
	l.current = l.getc()
	switch {
	default:
		goto yyrule23
	case l.current == 'e':
		goto yystate52
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate52:
	l.current = l.getc()
	switch {
	default:
		goto yyrule24
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate53:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'o':
		goto yystate54
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'n' || l.current >= 'p' && l.current <= 'z':
		goto yystate21
	}

yystate54:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 's':
		goto yystate55
	case l.current == 'v':
		goto yystate57
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'r' || l.current == 't' || l.current == 'u' || l.current >= 'w' && l.current <= 'z':
		goto yystate21
	}

yystate55:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate56
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate56:
	l.current = l.getc()
	switch {
	default:
		goto yyrule31
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate57:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate58
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate58:
	l.current = l.getc()
	switch {
	default:
		goto yyrule38
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate59:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate60
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate60:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'h':
		goto yystate61
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'g' || l.current >= 'i' && l.current <= 'z':
		goto yystate21
	}

yystate61:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate62
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate62:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'r':
		goto yystate63
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate63:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'w':
		goto yystate64
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'v' || l.current >= 'x' && l.current <= 'z':
		goto yystate21
	}

yystate64:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate65
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate65:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 's':
		goto yystate66
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'r' || l.current >= 't' && l.current <= 'z':
		goto yystate21
	}

yystate66:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate67
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate67:
	l.current = l.getc()
	switch {
	default:
		goto yyrule37
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate68:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate69
	case l.current == 'l':
		goto yystate75
	case l.current == 'r':
		goto yystate80
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'k' || l.current >= 'm' && l.current <= 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate69:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'r':
		goto yystate70
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate70:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'f':
		goto yystate71
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'e' || l.current >= 'g' && l.current <= 'z':
		goto yystate21
	}

yystate71:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'o':
		goto yystate72
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'n' || l.current >= 'p' && l.current <= 'z':
		goto yystate21
	}

yystate72:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'r':
		goto yystate73
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate73:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'm':
		goto yystate74
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'l' || l.current >= 'n' && l.current <= 'z':
		goto yystate21
	}

yystate74:
	l.current = l.getc()
	switch {
	default:
		goto yyrule42
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate75:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate76
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate76:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'a':
		goto yystate77
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'b' && l.current <= 'z':
		goto yystate21
	}

yystate77:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 's':
		goto yystate78
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'r' || l.current >= 't' && l.current <= 'z':
		goto yystate21
	}

yystate78:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate79
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate79:
	l.current = l.getc()
	switch {
	default:
		goto yyrule44
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate80:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate81
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate81:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'n':
		goto yystate82
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'm' || l.current >= 'o' && l.current <= 'z':
		goto yystate21
	}

yystate82:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate83
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate83:
	l.current = l.getc()
	switch {
	default:
		goto yyrule8
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate84:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate85
	case l.current == 'o':
		goto yystate94
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'n' || l.current >= 'p' && l.current <= 'z':
		goto yystate21
	}

yystate85:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 's':
		goto yystate86
	case l.current == 't':
		goto yystate90
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'r' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate86:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate87
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate87:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'z':
		goto yystate88
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'y':
		goto yystate21
	}

yystate88:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate89
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate89:
	l.current = l.getc()
	switch {
	default:
		goto yyrule12
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate90:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'u':
		goto yystate91
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 't' || l.current >= 'v' && l.current <= 'z':
		goto yystate21
	}

yystate91:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'r':
		goto yystate92
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate92:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'n':
		goto yystate93
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'm' || l.current >= 'o' && l.current <= 'z':
		goto yystate21
	}

yystate93:
	l.current = l.getc()
	switch {
	default:
		goto yyrule43
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate94:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate95
	case l.current == 'u':
		goto yystate99
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'v' && l.current <= 'z':
		goto yystate21
	}

yystate95:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'a':
		goto yystate96
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'b' && l.current <= 'z':
		goto yystate21
	}

yystate96:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate97
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate97:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate98
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate98:
	l.current = l.getc()
	switch {
	default:
		goto yyrule39
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate99:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate100
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate100:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate101
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate101:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'n':
		goto yystate102
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'm' || l.current >= 'o' && l.current <= 'z':
		goto yystate21
	}

yystate102:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'g':
		goto yystate103
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'f' || l.current >= 'h' && l.current <= 'z':
		goto yystate21
	}

yystate103:
	l.current = l.getc()
	switch {
	default:
		goto yyrule41
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate104:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate105
	case l.current == 't':
		goto yystate108
	case l.current == 'u':
		goto yystate113
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 's' || l.current >= 'v' && l.current <= 'z':
		goto yystate21
	}

yystate105:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'z':
		goto yystate106
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'y':
		goto yystate21
	}

yystate106:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate107
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate107:
	l.current = l.getc()
	switch {
	default:
		goto yyrule11
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate108:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate109
	case l.current == 'o':
		goto yystate111
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'n' || l.current >= 'p' && l.current <= 'z':
		goto yystate21
	}

yystate109:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'p':
		goto yystate110
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'o' || l.current >= 'q' && l.current <= 'z':
		goto yystate21
	}

yystate110:
	l.current = l.getc()
	switch {
	default:
		goto yyrule34
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate111:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'p':
		goto yystate112
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'o' || l.current >= 'q' && l.current <= 'z':
		goto yystate21
	}

yystate112:
	l.current = l.getc()
	switch {
	default:
		goto yyrule33
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate113:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'r':
		goto yystate114
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate114:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'r':
		goto yystate115
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate115:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'o':
		goto yystate116
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'n' || l.current >= 'p' && l.current <= 'z':
		goto yystate21
	}

yystate116:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'u':
		goto yystate117
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 't' || l.current >= 'v' && l.current <= 'z':
		goto yystate21
	}

yystate117:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'n':
		goto yystate118
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'm' || l.current >= 'o' && l.current <= 'z':
		goto yystate21
	}

yystate118:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'd':
		goto yystate119
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'c' || l.current >= 'e' && l.current <= 'z':
		goto yystate21
	}

yystate119:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate120
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate120:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'n':
		goto yystate121
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'm' || l.current >= 'o' && l.current <= 'z':
		goto yystate21
	}

yystate121:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'g':
		goto yystate122
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'f' || l.current >= 'h' && l.current <= 'z':
		goto yystate21
	}

yystate122:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 's':
		goto yystate123
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'r' || l.current >= 't' && l.current <= 'z':
		goto yystate21
	}

yystate123:
	l.current = l.getc()
	switch {
	default:
		goto yyrule40
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate124:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'h':
		goto yystate125
	case l.current == 'o':
		goto yystate135
	case l.current == 'r':
		goto yystate147
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'g' || l.current >= 'i' && l.current <= 'n' || l.current == 'p' || l.current == 'q' || l.current >= 's' && l.current <= 'z':
		goto yystate21
	}

yystate125:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'a':
		goto yystate126
	case l.current == 'e':
		goto yystate133
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'b' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate126:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'n':
		goto yystate127
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'm' || l.current >= 'o' && l.current <= 'z':
		goto yystate21
	}

yystate127:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'k':
		goto yystate128
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'j' || l.current >= 'l' && l.current <= 'z':
		goto yystate21
	}

yystate128:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == ' ':
		goto yystate129
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate129:
	l.current = l.getc()
	switch {
	default:
		goto yyabort
	case l.current == 'y':
		goto yystate130
	}

yystate130:
	l.current = l.getc()
	switch {
	default:
		goto yyabort
	case l.current == 'o':
		goto yystate131
	}

yystate131:
	l.current = l.getc()
	switch {
	default:
		goto yyabort
	case l.current == 'u':
		goto yystate132
	}

yystate132:
	l.current = l.getc()
	goto yyrule45

yystate133:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'n':
		goto yystate134
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'm' || l.current >= 'o' && l.current <= 'z':
		goto yystate21
	}

yystate134:
	l.current = l.getc()
	switch {
	default:
		goto yyrule36
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate135:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == '_':
		goto yystate136
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate136:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'd':
		goto yystate137
	case l.current == 'l':
		goto yystate142
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'c' || l.current >= 'e' && l.current <= 'k' || l.current >= 'm' && l.current <= 'z':
		goto yystate21
	}

yystate137:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate138
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate138:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'g':
		goto yystate139
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'f' || l.current >= 'h' && l.current <= 'z':
		goto yystate21
	}

yystate139:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate140
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate140:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 't':
		goto yystate141
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 's' || l.current >= 'u' && l.current <= 'z':
		goto yystate21
	}

yystate141:
	l.current = l.getc()
	switch {
	default:
		goto yyrule10
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate142:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'o':
		goto yystate143
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'n' || l.current >= 'p' && l.current <= 'z':
		goto yystate21
	}

yystate143:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'g':
		goto yystate144
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'f' || l.current >= 'h' && l.current <= 'z':
		goto yystate21
	}

yystate144:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'i':
		goto yystate145
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'h' || l.current >= 'j' && l.current <= 'z':
		goto yystate21
	}

yystate145:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'c':
		goto yystate146
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current == 'a' || l.current == 'b' || l.current >= 'd' && l.current <= 'z':
		goto yystate21
	}

yystate146:
	l.current = l.getc()
	switch {
	default:
		goto yyrule9
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate147:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'u':
		goto yystate148
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 't' || l.current >= 'v' && l.current <= 'z':
		goto yystate21
	}

yystate148:
	l.current = l.getc()
	switch {
	default:
		goto yyrule47
	case l.current == 'e':
		goto yystate149
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'd' || l.current >= 'f' && l.current <= 'z':
		goto yystate21
	}

yystate149:
	l.current = l.getc()
	switch {
	default:
		goto yyrule6
	case l.current >= '0' && l.current <= '9' || l.current >= 'A' && l.current <= 'Z' || l.current == '_' || l.current >= 'a' && l.current <= 'z':
		goto yystate21
	}

yystate150:
	l.current = l.getc()
	goto yyrule15

yystate151:
	l.current = l.getc()
	goto yyrule16

yyrule1: // [ \t\r\n]+
	{

		// Игнорируем пробелы
		goto yystate0
	}
yyrule2: // "+"
	{
		return PLUS
	}
yyrule3: // "-"
	{
		return MINUS
	}
yyrule4: // "*"
	{
		return MULT
	}
yyrule5: // "/"
	{
		return DIV
	}
yyrule6: // "true"
	{

		yyLval.boolean = true
		return TRUE
	}
yyrule7: // "false"
	{

		yyLval.boolean = false
		return FALSE
	}
yyrule8: // "print"
	{

		return PRINT
	}
yyrule9: // "to_logic"
	{
		return TO_LOGIC_CAST
	}
yyrule10: // "to_digit"
	{
		return TO_DIGIT_CAST
	}
yyrule11: // "size"
	{
		return SIZE_OPERATOR
	}
yyrule12: // "resize"
	{
		return RESIZE_OPERATOR
	}
yyrule13: // "["
	{
		return SQUARE_BRACE_LEFT
	}
yyrule14: // "]"
	{
		return SQUARE_BRACE_RIGHT
	}
yyrule15: // "{"
	{
		return GROUP_BRACE_LEFT
	}
yyrule16: // "}"
	{
		return GROUP_BRACE_RIGHT
	}
yyrule17: // "("
	{
		return DEFAULT_BRACE_LEFT
	}
yyrule18: // ")"
	{
		return DEFAULT_BRACE_RIGHT
	}
yyrule19: // "digit"
	{

		yyLval.dType = intr.Int
		return DIGIT_TYPE
	}
yyrule20: // "logic"
	{

		yyLval.dType = intr.Bool
		return LOGIC_TYPE
	}
yyrule21: // "="
	{
		return ASSIGNMENT_OPERATOR
	}
yyrule22: // "eq"
	{
		return EQUALS
	}
yyrule23: // "lt"
	{
		return LOWER_THEN
	}
yyrule24: // "lte"
	{
		return LOWER_THEN_OR_EQUALS
	}
yyrule25: // "gt"
	{
		return GREATER_THEN
	}
yyrule26: // "gte"
	{
		return GREATER_THEN_OR_EQUALS
	}
yyrule27: // ","
	{
		return COMMA
	}
yyrule28: // ";"
	{
		return STATEMENT_END
	}
yyrule29: // "!"
	{
		return NOT
	}
yyrule30: // "&&"
	{
		return AND
	}
yyrule31: // "most"
	{
		return MOST
	}
yyrule32: // "for"
	{
		return FOR
	}
yyrule33: // "stop"
	{
		return STOP
	}
yyrule34: // "step"
	{
		return STEP
	}
yyrule35: // "check"
	{
		return CHECK
	}
yyrule36: // "then"
	{
		return THEN
	}
yyrule37: // "otherwise"
	{
		return OTHERWISE
	}
yyrule38: // "move"
	{
		return MOVE_OPERATOR
	}
yyrule39: // "rotate"
	{
		return ROTATE_OPERATOR
	}
yyrule40: // "surroundings"
	{
		return SURROUNDINGS
	}
yyrule41: // "routing"
	{
		return FUNCTION_DECL
	}
yyrule42: // "perform"
	{
		return FUNCTION_CALL
	}
yyrule43: // "return"
	{
		return RETURN
	}
yyrule44: // "please"
	{
		return PLEASE
	}
yyrule45: // "thank you"
	{
		return THANK_YOU

	}
yyrule46: // {D}
	{

		val, _ := strconv.Atoi(string(l.buf))
		yyLval.num = val
		return DECIMAL
	}
yyrule47: // [A-Za-z_][A-Za-z_0-9]*
	{

		val := string(l.buf)
		yyLval.str = val
		return NAME
	}
yyrule48: // \0
	{

		return 0 // EOF
	}
yyrule49: // .
	if true { // avoid go vet determining the below panic will not be reached

		return -1
	}
	panic("unreachable")

yyabort: // no lexem recognized
	// silence unused label errors for build and satisfy go vet reachability analysis
	{
		if false {
			goto yyabort
		}
		if false {
			goto yystate0
		}
		if false {
			goto yystate1
		}
	}

	return 0
}
