// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:3
package main

import __yyfmt__ "fmt"

//line parser.y:3

import (
	"fmt"
	intr "lab3/interpreter"
	"os"
)

var __rootAST intr.AstNode = nil

func GetRoot() intr.AstNode {
	return __rootAST
}

type paramStruct struct {
	names []string
	types []intr.Variable
}

//line parser.y:20
type yySymType struct {
	yys      int
	num      int
	str      string
	boolean  bool
	dType    intr.VarT
	node     intr.AstNode
	nodeList []intr.AstNode
	params   paramStruct
	variable intr.Variable
}

const PRINT = 57346
const PLUS = 57347
const MINUS = 57348
const MULT = 57349
const DIV = 57350
const TRUE = 57351
const FALSE = 57352
const TO_LOGIC_CAST = 57353
const TO_DIGIT_CAST = 57354
const SIZE_OPERATOR = 57355
const RESIZE_OPERATOR = 57356
const SQUARE_BRACE_LEFT = 57357
const SQUARE_BRACE_RIGHT = 57358
const GROUP_BRACE_LEFT = 57359
const GROUP_BRACE_RIGHT = 57360
const DEFAULT_BRACE_LEFT = 57361
const DEFAULT_BRACE_RIGHT = 57362
const DIGIT_TYPE = 57363
const LOGIC_TYPE = 57364
const ASSIGNMENT_OPERATOR = 57365
const EQ = 57366
const LT = 57367
const LTE = 57368
const GT = 57369
const GTE = 57370
const EQ_MAP = 57371
const LT_MAP = 57372
const LTE_MAP = 57373
const GT_MAP = 57374
const GTE_MAP = 57375
const COMMA = 57376
const STATEMENT_END = 57377
const NOT = 57378
const AND = 57379
const MOST = 57380
const FOR = 57381
const STOP = 57382
const STEP = 57383
const CHECK = 57384
const THEN = 57385
const OTHERWISE = 57386
const MOVE_OPERATOR = 57387
const ROTATE_OPERATOR = 57388
const SURROUNDINGS = 57389
const FUNCTION_DECL = 57390
const FUNCTION_CALL = 57391
const RETURN = 57392
const PLEASE = 57393
const THANK_YOU = 57394
const NAME = 57395
const HEX = 57396
const OCTAL = 57397
const DECIMAL = 57398

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PRINT",
	"PLUS",
	"MINUS",
	"MULT",
	"DIV",
	"TRUE",
	"FALSE",
	"TO_LOGIC_CAST",
	"TO_DIGIT_CAST",
	"SIZE_OPERATOR",
	"RESIZE_OPERATOR",
	"SQUARE_BRACE_LEFT",
	"SQUARE_BRACE_RIGHT",
	"GROUP_BRACE_LEFT",
	"GROUP_BRACE_RIGHT",
	"DEFAULT_BRACE_LEFT",
	"DEFAULT_BRACE_RIGHT",
	"DIGIT_TYPE",
	"LOGIC_TYPE",
	"ASSIGNMENT_OPERATOR",
	"EQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"EQ_MAP",
	"LT_MAP",
	"LTE_MAP",
	"GT_MAP",
	"GTE_MAP",
	"COMMA",
	"STATEMENT_END",
	"NOT",
	"AND",
	"MOST",
	"FOR",
	"STOP",
	"STEP",
	"CHECK",
	"THEN",
	"OTHERWISE",
	"MOVE_OPERATOR",
	"ROTATE_OPERATOR",
	"SURROUNDINGS",
	"FUNCTION_DECL",
	"FUNCTION_CALL",
	"RETURN",
	"PLEASE",
	"THANK_YOU",
	"NAME",
	"HEX",
	"OCTAL",
	"DECIMAL",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:434

// Функция вывода ошибок, требуемая для yyLexer
func (l *lexerCtx) Error(s string) {
	fmt.Fprintf(os.Stderr, "Ошибка: %s\n", s)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 279

var yyAct = [...]int8{
	3, 26, 2, 19, 31, 11, 113, 106, 102, 32,
	33, 29, 30, 13, 87, 28, 21, 67, 39, 35,
	42, 20, 38, 109, 43, 98, 46, 47, 69, 27,
	17, 18, 94, 86, 64, 65, 73, 45, 105, 25,
	32, 33, 71, 13, 100, 72, 75, 76, 15, 36,
	35, 14, 104, 37, 114, 13, 34, 119, 101, 16,
	17, 18, 12, 111, 23, 66, 82, 83, 84, 118,
	61, 62, 17, 18, 89, 80, 81, 13, 15, 91,
	36, 14, 95, 107, 37, 41, 79, 34, 97, 16,
	15, 116, 12, 14, 17, 18, 19, 45, 17, 18,
	63, 16, 68, 45, 12, 44, 110, 108, 24, 1,
	112, 13, 15, 19, 115, 14, 19, 117, 19, 24,
	59, 60, 90, 16, 96, 103, 12, 40, 17, 18,
	59, 60, 49, 50, 51, 52, 53, 54, 55, 56,
	57, 58, 24, 10, 9, 85, 15, 5, 8, 14,
	22, 48, 7, 6, 4, 0, 0, 16, 0, 0,
	12, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	58, 0, 99, 49, 50, 51, 52, 53, 54, 55,
	56, 57, 58, 0, 92, 49, 50, 51, 52, 53,
	54, 55, 56, 57, 58, 0, 88, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 0, 74, 49,
	50, 51, 52, 53, 54, 55, 56, 57, 58, 93,
	70, 0, 0, 0, 0, 0, 0, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 78, 0, 0,
	0, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	58, 77, 0, 0, 0, 0, 0, 0, 0, 49,
	50, 51, 52, 53, 54, 55, 56, 57, 58, 49,
	50, 51, 52, 53, 54, 55, 56, 57, 58,
}

var yyPact = [...]int16{
	9, -1000, 9, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -32, 127, 20, 0, -31, 0, -1000, -1000, -1000,
	104, -33, 0, 82, 0, 0, 108, 115, 63, 31,
	31, -1000, -1000, -1000, -1000, 0, -36, 93, -12, 185,
	0, 22, 17, 173, 0, 0, 235, 217, 69, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 0,
	0, 31, 31, 31, -1000, -1000, 125, 14, 88, -39,
	-1000, 161, 0, 77, -1000, 149, 203, -1000, -3, 9,
	63, 63, -1000, -1000, -1000, -1000, 0, -16, -1000, 137,
	24, -45, -1000, -1000, -1000, 107, 18, 245, -46, -1000,
	66, 77, -1000, -21, 0, -1000, 46, 9, -47, 37,
	245, 9, 73, -1000, 9, 51, -1000, 39, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 0, 2, 154, 1, 29, 15, 4, 153, 152,
	148, 147, 144, 143, 5, 64, 124, 122, 109,
}

var yyR1 = [...]int8{
	0, 18, 2, 2, 1, 1, 1, 1, 1, 1,
	1, 8, 11, 11, 3, 3, 9, 9, 10, 13,
	14, 14, 12, 17, 17, 15, 15, 16, 16, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	5, 5, 5, 6, 6, 6, 6, 6, 6, 7,
	7, 7, 7, 7, 7, 7,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 5, 4, 5, 5, 6, 10, 6, 9, 3,
	1, 1, 9, 4, 2, 4, 3, 3, 1, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
	3, 3, 1, 3, 3, 3, 2, 2, 1, 1,
	1, 1, 3, 5, 2, 1,
}

var yyChk = [...]int16{
	-1000, -18, -2, -1, -3, -11, -8, -9, -10, -12,
	-13, -14, 53, 4, 42, 39, 50, 21, 22, -1,
	53, 48, 23, -15, 15, 19, -4, -5, -6, 11,
	12, -7, 9, 10, 56, 19, 49, 53, 53, -4,
	23, -15, 53, -4, 23, 15, -4, -4, 43, 24,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 5,
	6, 7, 8, 37, -7, -7, -5, 53, -15, 40,
	35, -4, 23, 19, 35, -4, -4, 16, 20, 17,
	-6, -6, -7, -7, -7, 20, 19, 53, 35, -4,
	-17, -14, 35, 16, 35, -2, -16, -4, 41, 35,
	20, 34, 53, 18, 34, 20, 53, 17, -14, 44,
	-4, 17, -2, 53, 17, -2, 18, -2, 18, 18,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 4, 5, 6, 7, 8, 9,
	10, 0, 0, 0, 0, 0, 0, 20, 21, 3,
	0, 0, 0, 0, 0, 0, 0, 39, 42, 0,
	0, 48, 49, 50, 51, 0, 0, 55, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 29,
	30, 31, 32, 33, 34, 35, 36, 37, 38, 0,
	0, 0, 0, 0, 46, 47, 0, 0, 54, 0,
	19, 0, 0, 0, 12, 0, 0, 26, 0, 0,
	40, 41, 43, 44, 45, 52, 0, 0, 14, 0,
	0, 0, 13, 25, 11, 0, 0, 28, 0, 15,
	0, 0, 24, 17, 0, 53, 0, 0, 0, 0,
	27, 0, 0, 23, 0, 0, 22, 0, 18, 16,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:120
		{
			__rootAST = yyDollar[1].node
			fmt.Println("\n[Parser]: AstPart=ok")
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:129
		{
			statements := intr.NewStatementListNode()
			statements.PushStatement(yyDollar[1].node)
			yyVAL.node = statements
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:135
		{
			statements := yyDollar[1].node.(*intr.StatementListNode)
			statements.PushStatement(yyDollar[2].node)
			yyVAL.node = statements
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:143
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:147
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:151
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:155
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:159
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:163
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:167
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:174
		{
			yyVAL.node = intr.NewPrintNode(yyDollar[3].node)
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:180
		{
			yyVAL.node = intr.NewAssignNode(yyDollar[1].str, yyDollar[3].node)
		}
	case 13:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:184
		{
			elem := intr.NewArrayElemNode(yyDollar[2].nodeList, yyDollar[1].str)
			yyVAL.node = intr.NewArrayAssignNode(elem, yyDollar[4].node)
		}
	case 14:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:191
		{
			yyVAL.node = intr.NewScalarDeclNode(yyDollar[2].str, yyDollar[4].node, yyDollar[1].dType)
		}
	case 15:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:195
		{
			yyVAL.node = intr.NewArrayDeclNode(yyDollar[1].dType, yyDollar[2].str, yyDollar[3].nodeList, yyDollar[5].node)
		}
	case 16:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser.y:202
		{
			yyVAL.node = intr.NewIfStatementNode(yyDollar[2].node, yyDollar[5].node, yyDollar[9].node)
		}
	case 17:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:206
		{
			yyVAL.node = intr.NewIfStatementNode(yyDollar[2].node, yyDollar[5].node, nil)
		}
	case 18:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.y:213
		{
			yyVAL.node = intr.NewForStatementNode(yyDollar[2].str, yyDollar[4].str, yyDollar[6].str, yyDollar[8].node)
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:219
		{
			yyVAL.node = yyDollar[2].node
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:226
		{
			yyVAL.dType = yyDollar[1].dType
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:230
		{
			yyVAL.dType = yyDollar[1].dType
		}
	case 22:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.y:237
		{
			var res intr.Variable = nil
			if yyDollar[1].dType == intr.Int {
				res = intr.NewVariableInt(0)
			}
			if yyDollar[1].dType == intr.Bool {
				res = intr.NewVariableBool(false)
			}
			yyVAL.node = intr.NewFunctionDeclNode(yyDollar[3].str, yyDollar[5].params.types, yyDollar[5].params.names, res, yyDollar[8].node)
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:251
		{
			names := yyDollar[1].params.names
			types := yyDollar[1].params.types
			names = append(names, yyDollar[4].str)
			if yyDollar[3].dType == intr.Int {
				types = append(types, intr.NewVariableInt(0))
			}
			if yyDollar[3].dType == intr.Bool {
				types = append(types, intr.NewVariableBool(false))
			}

			yyVAL.params = paramStruct{names, types}
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:265
		{
			names := []string{}
			types := []intr.Variable{}
			names = append(names, yyDollar[2].str)
			if yyDollar[1].dType == intr.Int {
				types = append(types, intr.NewVariableInt(0))
			}
			if yyDollar[1].dType == intr.Bool {
				types = append(types, intr.NewVariableBool(false))
			}

			yyVAL.params = paramStruct{names, types}
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:281
		{
			nodes := append(yyDollar[1].nodeList, yyDollar[3].node)
			yyVAL.nodeList = nodes
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:286
		{
			nodes := []intr.AstNode{}
			nodes = append(nodes, yyDollar[2].node)
			yyVAL.nodeList = nodes
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:294
		{
			nodes := append(yyDollar[1].nodeList, yyDollar[3].node)
			yyVAL.nodeList = nodes
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:299
		{
			nodes := []intr.AstNode{}
			nodes = append(nodes, yyDollar[1].node)
			yyVAL.nodeList = nodes
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:307
		{
			yyVAL.node = intr.NewEqReduceNode(yyDollar[1].node)
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:311
		{
			yyVAL.node = intr.NewLtReduceNode(yyDollar[1].node)
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:315
		{
			yyVAL.node = intr.NewLteReduceNode(yyDollar[1].node)
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:319
		{
			yyVAL.node = intr.NewGtReduceNode(yyDollar[1].node)
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:323
		{
			yyVAL.node = intr.NewGteReduceNode(yyDollar[1].node)
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:327
		{
			yyVAL.node = intr.NewEqMapNode(yyDollar[1].node)
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:331
		{
			yyVAL.node = intr.NewLtMapNode(yyDollar[1].node)
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:335
		{
			yyVAL.node = intr.NewLteMapNode(yyDollar[1].node)
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:339
		{
			yyVAL.node = intr.NewGtMapNode(yyDollar[1].node)
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:343
		{
			yyVAL.node = intr.NewGteMapNode(yyDollar[1].node)
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:348
		{
			yyVAL.node = yyDollar[1].node
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:355
		{
			yyVAL.node = intr.NewAddNode(yyDollar[1].node, yyDollar[3].node)
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:359
		{
			yyVAL.node = intr.NewSubNode(yyDollar[1].node, yyDollar[3].node)
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:364
		{
			yyVAL.node = yyDollar[1].node
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:371
		{
			yyVAL.node = intr.NewMulNode(yyDollar[1].node, yyDollar[3].node)

		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:376
		{
			yyVAL.node = intr.NewDivNode(yyDollar[1].node, yyDollar[3].node)
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:380
		{
			yyVAL.node = intr.NewAndNode(yyDollar[1].node, yyDollar[3].node)
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:384
		{
			yyVAL.node = intr.NewToBooleanCastNode(yyDollar[2].node)
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:388
		{
			yyVAL.node = intr.NewToIntegerCastNode(yyDollar[2].node)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:394
		{
			yyVAL.node = yyDollar[1].node
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:401
		{
			yyVAL.node = intr.NewBooleanNode(yyDollar[1].boolean)
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:405
		{
			yyVAL.node = intr.NewBooleanNode(yyDollar[1].boolean)
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:409
		{
			yyVAL.node = intr.NewIntegerNode(yyDollar[1].num)

		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:414
		{
			yyVAL.node = yyDollar[2].node
		}
	case 53:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:418
		{
			yyVAL.node = intr.NewFunctionCallNode(yyDollar[2].str, yyDollar[4].nodeList)
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:422
		{
			yyVAL.node = intr.NewArrayElemNode(yyDollar[2].nodeList, yyDollar[1].str)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:426
		{
			yyVAL.node = intr.NewNameNode(yyDollar[1].str)
		}
	}
	goto yystack /* stack new state and value */
}
