// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:3
package main

import __yyfmt__ "fmt"

//line parser.y:3

import (
	"fmt"
	intr "lab3/interpreter"
	"os"
)

var __rootAST intr.AstNode = nil

func GetRoot() intr.AstNode {
	return __rootAST
}

//line parser.y:16
type yySymType struct {
	yys      int
	num      int
	str      string
	boolean  bool
	dType    intr.VarT
	node     intr.AstNode
	nodeList []intr.AstNode
}

const PRINT = 57346
const PLUS = 57347
const MINUS = 57348
const MULT = 57349
const DIV = 57350
const TRUE = 57351
const FALSE = 57352
const TO_LOGIC_CAST = 57353
const TO_DIGIT_CAST = 57354
const SIZE_OPERATOR = 57355
const RESIZE_OPERATOR = 57356
const SQUARE_BRACE_LEFT = 57357
const SQUARE_BRACE_RIGHT = 57358
const GROUP_BRACE_LEFT = 57359
const GROUP_BRACE_RIGHT = 57360
const DEFAULT_BRACE_LEFT = 57361
const DEFAULT_BRACE_RIGHT = 57362
const DIGIT_TYPE = 57363
const LOGIC_TYPE = 57364
const ASSIGNMENT_OPERATOR = 57365
const EQ = 57366
const LT = 57367
const LTE = 57368
const GT = 57369
const GTE = 57370
const EQ_MAP = 57371
const LT_MAP = 57372
const LTE_MAP = 57373
const GT_MAP = 57374
const GTE_MAP = 57375
const COMMA = 57376
const STATEMENT_END = 57377
const NOT = 57378
const AND = 57379
const MOST = 57380
const FOR = 57381
const STOP = 57382
const STEP = 57383
const CHECK = 57384
const THEN = 57385
const OTHERWISE = 57386
const MOVE_OPERATOR = 57387
const ROTATE_OPERATOR = 57388
const SURROUNDINGS = 57389
const FUNCTION_DECL = 57390
const FUNCTION_CALL = 57391
const RETURN = 57392
const PLEASE = 57393
const THANK_YOU = 57394
const NAME = 57395
const HEX = 57396
const OCTAL = 57397
const DECIMAL = 57398

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PRINT",
	"PLUS",
	"MINUS",
	"MULT",
	"DIV",
	"TRUE",
	"FALSE",
	"TO_LOGIC_CAST",
	"TO_DIGIT_CAST",
	"SIZE_OPERATOR",
	"RESIZE_OPERATOR",
	"SQUARE_BRACE_LEFT",
	"SQUARE_BRACE_RIGHT",
	"GROUP_BRACE_LEFT",
	"GROUP_BRACE_RIGHT",
	"DEFAULT_BRACE_LEFT",
	"DEFAULT_BRACE_RIGHT",
	"DIGIT_TYPE",
	"LOGIC_TYPE",
	"ASSIGNMENT_OPERATOR",
	"EQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"EQ_MAP",
	"LT_MAP",
	"LTE_MAP",
	"GT_MAP",
	"GTE_MAP",
	"COMMA",
	"STATEMENT_END",
	"NOT",
	"AND",
	"MOST",
	"FOR",
	"STOP",
	"STEP",
	"CHECK",
	"THEN",
	"OTHERWISE",
	"MOVE_OPERATOR",
	"ROTATE_OPERATOR",
	"SURROUNDINGS",
	"FUNCTION_DECL",
	"FUNCTION_CALL",
	"RETURN",
	"PLEASE",
	"THANK_YOU",
	"NAME",
	"HEX",
	"OCTAL",
	"DECIMAL",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:324

// Функция вывода ошибок, требуемая для yyLexer
func (l *lexerCtx) Error(s string) {
	fmt.Fprintf(os.Stderr, "Ошибка: %s\n", s)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 167

var yyAct = [...]int8{
	3, 26, 27, 16, 2, 26, 27, 23, 24, 11,
	71, 29, 65, 31, 17, 29, 11, 72, 11, 69,
	54, 67, 11, 78, 32, 22, 14, 15, 19, 21,
	77, 18, 70, 14, 15, 14, 15, 25, 74, 14,
	15, 73, 58, 1, 13, 30, 9, 12, 28, 30,
	5, 13, 28, 13, 12, 8, 12, 13, 10, 53,
	12, 51, 52, 68, 7, 10, 6, 10, 4, 16,
	0, 10, 59, 60, 48, 49, 16, 16, 75, 76,
	46, 47, 0, 0, 46, 47, 61, 62, 63, 36,
	37, 38, 39, 40, 41, 42, 43, 44, 45, 64,
	0, 0, 0, 0, 50, 0, 0, 0, 35, 36,
	37, 38, 39, 40, 41, 42, 43, 44, 45, 0,
	66, 36, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 57, 56, 20, 0, 36, 37, 38, 39, 40,
	41, 42, 43, 44, 45, 0, 0, 0, 0, 0,
	0, 0, 33, 34, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 55,
}

var yyPact = [...]int16{
	18, -1000, 18, -1000, -1000, -1000, -1000, -1000, -1000, -39,
	8, 9, -4, -40, -1000, -1000, -1000, 1, -4, -4,
	65, 75, 67, -8, -8, -1000, -1000, -1000, -1000, -4,
	-1000, -20, -4, 97, 111, 25, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -4, -4, -8, -8,
	-8, -1000, -1000, 79, -41, 85, -1000, -14, 18, 67,
	67, -1000, -1000, -1000, -1000, -22, -1000, -1000, 14, -43,
	-27, 24, 21, 18, 18, 12, 5, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 0, 4, 68, 133, 29, 25, 37, 66, 64,
	55, 50, 46, 43,
}

var yyR1 = [...]int8{
	0, 13, 2, 2, 1, 1, 1, 1, 1, 8,
	11, 3, 9, 9, 10, 12, 12, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 5, 5,
	5, 6, 6, 6, 6, 6, 6, 7, 7, 7,
	7, 7,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 1, 1, 1, 1, 1, 5,
	4, 5, 10, 6, 9, 1, 1, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 1, 3, 3,
	1, 3, 3, 3, 2, 2, 1, 1, 1, 1,
	3, 1,
}

var yyChk = [...]int16{
	-1000, -13, -2, -1, -3, -11, -8, -9, -10, -12,
	53, 4, 42, 39, 21, 22, -1, 53, 23, 19,
	-4, -5, -6, 11, 12, -7, 9, 10, 56, 19,
	53, 53, 23, -4, -4, 43, 24, 25, 26, 27,
	28, 29, 30, 31, 32, 33, 5, 6, 7, 8,
	37, -7, -7, -5, 40, -4, 35, 20, 17, -6,
	-6, -7, -7, -7, 20, 53, 35, 35, -2, 41,
	18, 53, 44, 17, 17, -2, -2, 18, 18,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 4, 5, 6, 7, 8, 0,
	0, 0, 0, 0, 15, 16, 3, 0, 0, 0,
	0, 27, 30, 0, 0, 36, 37, 38, 39, 0,
	41, 0, 0, 0, 0, 0, 17, 18, 19, 20,
	21, 22, 23, 24, 25, 26, 0, 0, 0, 0,
	0, 34, 35, 0, 0, 0, 10, 0, 0, 28,
	29, 31, 32, 33, 40, 0, 11, 9, 0, 0,
	13, 0, 0, 0, 0, 0, 0, 14, 12,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:112
		{
			__rootAST = yyDollar[1].node
			fmt.Println("\n[Parser]: AstPart=ok")
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:121
		{
			statements := intr.NewStatementListNode()
			statements.PushStatement(yyDollar[1].node)
			yyVAL.node = statements
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:127
		{
			statements := yyDollar[1].node.(*intr.StatementListNode)
			statements.PushStatement(yyDollar[2].node)
			yyVAL.node = statements
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:135
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:139
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:143
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:147
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:151
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:158
		{
			yyVAL.node = intr.NewPrintNode(yyDollar[3].node)
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:164
		{
			yyVAL.node = intr.NewAssignNode(yyDollar[1].str, yyDollar[3].node)
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:170
		{
			yyVAL.node = intr.NewScalarDeclNode(yyDollar[2].str, yyDollar[4].node, yyDollar[1].dType)
		}
	case 12:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser.y:177
		{
			yyVAL.node = intr.NewIfStatementNode(yyDollar[2].node, yyDollar[5].node, yyDollar[9].node)
		}
	case 13:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:181
		{
			yyVAL.node = intr.NewIfStatementNode(yyDollar[2].node, yyDollar[5].node, nil)
		}
	case 14:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.y:188
		{
			yyVAL.node = intr.NewForStatementNode(yyDollar[2].str, yyDollar[4].str, yyDollar[6].str, yyDollar[8].node)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:194
		{
			yyVAL.dType = yyDollar[1].dType
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:198
		{
			yyVAL.dType = yyDollar[1].dType
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:207
		{
			yyVAL.node = intr.NewEqReduceNode(yyDollar[1].node)
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:211
		{
			yyVAL.node = intr.NewLtReduceNode(yyDollar[1].node)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:215
		{
			yyVAL.node = intr.NewLteReduceNode(yyDollar[1].node)
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:219
		{
			yyVAL.node = intr.NewGtReduceNode(yyDollar[1].node)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:223
		{
			yyVAL.node = intr.NewGteReduceNode(yyDollar[1].node)
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:227
		{
			yyVAL.node = intr.NewEqMapNode(yyDollar[1].node)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:231
		{
			yyVAL.node = intr.NewLtMapNode(yyDollar[1].node)
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:235
		{
			yyVAL.node = intr.NewLteMapNode(yyDollar[1].node)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:239
		{
			yyVAL.node = intr.NewGtMapNode(yyDollar[1].node)
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:243
		{
			yyVAL.node = intr.NewGteMapNode(yyDollar[1].node)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:247
		{
			yyVAL.node = yyDollar[1].node
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:254
		{
			yyVAL.node = intr.NewAddNode(yyDollar[1].node, yyDollar[3].node)
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:258
		{
			yyVAL.node = intr.NewSubNode(yyDollar[1].node, yyDollar[3].node)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:263
		{
			yyVAL.node = yyDollar[1].node
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:270
		{
			yyVAL.node = intr.NewMulNode(yyDollar[1].node, yyDollar[3].node)

		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:275
		{
			yyVAL.node = intr.NewDivNode(yyDollar[1].node, yyDollar[3].node)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:279
		{
			yyVAL.node = intr.NewAndNode(yyDollar[1].node, yyDollar[3].node)
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:283
		{
			yyVAL.node = intr.NewToBooleanCastNode(yyDollar[2].node)
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:287
		{
			yyVAL.node = intr.NewToIntegerCastNode(yyDollar[2].node)
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:292
		{
			yyVAL.node = yyDollar[1].node
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:299
		{
			yyVAL.node = intr.NewBooleanNode(yyDollar[1].boolean)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:303
		{
			yyVAL.node = intr.NewBooleanNode(yyDollar[1].boolean)
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:307
		{
			yyVAL.node = intr.NewIntegerNode(yyDollar[1].num)

		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:312
		{
			yyVAL.node = yyDollar[2].node
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:316
		{
			yyVAL.node = intr.NewNameNode(yyDollar[1].str)
		}
	}
	goto yystack /* stack new state and value */
}
